config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # static pages
  get '/about',   to: 'static_pages#about'
  get '/help',    to: 'static_pages#help'

  # Dynamic routes (users)
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  # Login routes (session)
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  get     '/account',   to: 'sessions#edit'
  patch   '/account',   to: 'sessions#update'
  delete  '/logout',    to: 'sessions#destroy'

  # Dynamic routes (listings)
  get  '/host',    to: 'listings#new'
  post '/host',    to: 'listings#create'

  # CRUD routes (RESTful)
  resources :users,     except: [ :new, :edit ]
  resources :listings,  except: [ :new ]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @listings = Listing.all
  end

  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%= provide(:heading, "About Us") %>

<p>Coming soon lah</p>

app/views/static_pages/help.html.erb
<%= provide(:heading, "How can we help?") %>

<div class="row">
  <div class="col-md-4 col-md-offset-1">
    <ul>
      <li>
        <a href="#"><p>How is the reservation price determined?</p></a>
      </li>
      <li>
        <a href="#"><p>Payments & Getting Paid</p></a>
      </li>
    </ul>
  </div>
  <div class="col-md-4 col-md-offset-2">
    <ul>
      <li>
        <a href="#"><p>What is the Pawscation cancellation policy?<p></a>
      </li>
      <li>
        <a href="mailto:ngxinde@gmail.com"><p>Reporting a Problem</p></a>
      </li>
    </ul>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= provide(:heading, "Meet your furrers") %>

<!-- Display listings -->
<div class="row">
  <% @listings.each do |listing| %>
  <%= link_to listing_path(listing.id, anchor: 'main'), class: 'listing-links' do %>
    <div class="col-md-4 show-listings">
      <div class="preview-listing" style="background-image: url(<%= listing.photo.url %>)"></div>
      <h4><%= listing.address %></h4>
      <p>Posted by: <%= listing.user.first_name %></p>
    </div>
  <% end %>
  <% end %>
</div>