config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # static pages
  get '/about',   to: 'static_pages#about'
  get '/help',    to: 'static_pages#help'

  # Dynamic routes (users)
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  # Login routes (session)
  get     '/login',     to: 'sessions#new'
  post    '/login',     to: 'sessions#create'
  get     '/account',   to: 'sessions#edit'
  patch   '/account',   to: 'sessions#update'
  delete  '/logout',    to: 'sessions#destroy'

  # Dynamic routes (listings)
  get  '/host',    to: 'listings#new'
  post '/host',    to: 'listings#create'

  # CRUD routes (RESTful)
  resources :users,     except: [ :new, :edit ]
  resources :listings,  except: [ :new ]
end

app/views/partials/_bodynav.html.erb
<div class="navbar navbar-inverse" id="main">
  <!-- Navbar left buttons -->
  <nav>
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "About", about_path(anchor: 'main'), class: 'navbar-links' %></li>
      <li><%= link_to "Help", help_path(anchor: 'main'), class: 'navbar-links' %></li>
    </ul>
  </nav>
</div>

app/views/partials/_carousel.html.erb
<div id="Carousel" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">
  <!-- <ol class="carousel-indicators">
      <li data-target="Carousel" data-slide-to="0" class="active"></li>
      <li data-target="Carousel" data-slide-to="1"></li>
      <li data-target="Carousel" data-slide-to="2"></li>
  </ol> -->

  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("carousel-img1.jpg", alt: "golden-retriever", class: "img-responsive") %>
    </div>

     <div class="item">
       <%= image_tag("carousel-img2.jpg", alt: "malamute", class: "img-responsive") %>
     </div>

     <div class="item">
       <%= image_tag("carousel-img3.jpg", alt: "samoyed", class: "img-responsive") %>
     </div>
  </div>

  <!-- <a class="left carousel-control" href="#Carousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#Carousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
  </a> -->
</div>

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="footer container">
  <small>
    &copy; Pawscation
    <a href="https://www.dota2.com/international/announcement"><strong>Dysol</strong></a>,
    All Rights Reserved. | Paws on Rails
  </small>
</footer>

app/views/partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <!-- Logo -->
  <nav class="navbar-brand">
    <%= link_to 'Pawscation', root_path, id: 'logo' %>
  </nav>
  <!-- Navbar right buttons -->
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <!-- show list dropdown -->
      <%= render 'partials/listing_dropdown' %>
        <!-- show account dropdown -->
        <li class="dropdown navlinks-right">
          <a href="#" class="dropdown-toggle navbar-links" data-toggle="dropdown">
            Wellos, Pawer <%= @current_user.first_name %> <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <li><%= link_to "My Account", account_path(anchor: 'main'), class: 'navbar-drop' %></li>
            <% if is_admin? %>
              <li><%= link_to "View All Accounts", users_path(anchor: 'main'), class: 'navbar-drop' %></li>
            <% end %>

            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, class: 'navbar-drop', method: 'delete' %></li>
          </ul>
        </li>
      <% else %>
        <li class="navlinks-right"><%= link_to "Sign up", signup_path(anchor: 'main'), class: 'navbar-links' %></li>
        <li class="navlinks-right"><%= link_to "Log in", login_path(anchor: 'main'), class: 'navbar-links' %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/partials/_listing_dropdown.html.erb
<li class="dropdown navlinks-right">
  <a href="#" class="dropdown-toggle navbar-links" data-toggle="dropdown">
    <span class="glyphicon glyphicon-home navbar-icons" aria-hidden="true"></span> Host
    <b class="caret"></b>
  </a>

  <ul class="dropdown-menu">
    <li>
      <%= link_to "Manage Listings ", user_path(id: current_user.id, anchor: 'main'), class: 'navbar-drop' %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to "List Your Space", host_path(anchor: 'main'), class: 'navbar-drop' %>
    </li>
  </ul>
</li>